# Generated by Django 5.2.8 on 2025-11-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=24)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('mfg', models.DateField()),
            ],
        ),
    ]
