# Generated by Django 5.2.8 on 2025-11-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=12)),
                ('orderdate', models.DateField()),
                ('location', models.CharField(max_length=32)),
            ],
        ),
    ]
