# Generated by Django 5.2.8 on 2025-12-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
