# Generated by Django 5.2.8 on 2025-11-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=32)),
                ('eloc', models.CharField(max_length=24)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
