# Generated by Django 5.2.8 on 2025-12-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32)),
                ('uemail', models.EmailField(max_length=254)),
                ('upassword', models.IntegerField()),
                ('uloc', models.CharField(max_length=32)),
            ],
        ),
    ]
